python main.py --output-images-dir poses_alpha0.0 --alpha 0.0 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.1 --alpha 0.1 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.2 --alpha 0.2 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.3 --alpha 0.3 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.4 --alpha 0.4 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.5 --alpha 0.5 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.6 --alpha 0.6 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.7 --alpha 0.7 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.8 --alpha 0.8 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha0.9 --alpha 0.9 --no_object_augmentation --use_poses
python main.py --output-images-dir poses_alpha1.0 --alpha 1.0 --no_object_augmentation --use_poses